# Generated by Django 2.1.7 on 2019-04-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='Restaurant name')),
                ('capacity', models.IntegerField(null=True, verbose_name='Capacity (nb. of people)')),
            ],
        ),
        migrations.CreateModel(
            name='SkiLift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='Ski lift name')),
            ],
        ),
        migrations.CreateModel(
            name='Slope',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='Slope name')),
                ('color', models.CharField(choices=[('blue', 'Blue (easy)'), ('red', 'Red (medium)'), ('black', 'Black (hard)')], max_length=80, null=True, verbose_name='Slope difficulty')),
                ('open', models.BooleanField(default=False, verbose_name='Slope open?')),
            ],
        ),
    ]
