# Generated by Django 2.1.7 on 2019-05-17 09:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoppingPlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('altitude', models.IntegerField(null=True, verbose_name='Altitude (in meters)')),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name="Stopping place's area")),
            ],
        ),
    ]
